/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "customers.index": [],
    "customers.create": [],
    "customers.store": [],
    "customers.show": [
        {
            "name": "customer",
            "required": true,
            "binding": "id"
        }
    ],
    "customers.edit": [
        {
            "name": "customer",
            "required": true,
            "binding": "id"
        }
    ],
    "customers.update": [
        {
            "name": "customer",
            "required": true,
            "binding": "id"
        }
    ],
    "customers.destroy": [
        {
            "name": "customer",
            "required": true,
            "binding": "id"
        }
    ],
    "customers.confirm-destroy": [
        {
            "name": "customer",
            "required": true,
            "binding": "id"
        }
    ],
    "customers.search": [],
    "customers.export": []
}
}
export {};
